### ISSUE TITLE
Checklist test sets

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/SolverTest.jl#8]
It would be great to complete the list of test sets for nlp and nls problems.
The checklist of current sets for `NLPModels`:
- [x] unconstrained problems (5 problems);
- [x] bound-constrained problems (6 problems);
- [x] equality-constrained problems (6 problems);
- [ ] bound and equality-constrained problems:
- [ ] inequality-constrained problems;
- [ ] mixed problems.

The checklist of current sets for `NLSModels`:
- [x] unconstrained problems (6 problems);
- [x] bound-constrained problems (7 problems);
- [x] equality-constrained problems (9 problems);
- [ ] bound and equality-constrained problems:
- [ ] inequality-constrained problems;
- [ ] mixed problems.
